#!/bin/bash
STOREPASS="forgotten"
OPENSSL_CONF_TEMPLATE="ssl.cnf.template"

##Criação do Servidor para Java.
rm -f serverJ.jks serverJ.pem
echo -e "serverJ\nDEI\nISEP\nPORTO\nPORTO\nPT\nyes" | keytool -genkey -v -alias serverJ -keyalg RSA -keysize 2048 \
	-validity 365 -keystore serverJ.jks -storepass ${STOREPASS}
keytool -exportcert -alias serverJ -keystore serverJ.jks -storepass ${STOREPASS} -rfc -file serverJ.pem

##Criação dos Clientes e Servidor para C.
for name in client1 client2 client3 client4 serverC; do
	echo "  ------------ Creating the file with certificate for ${name}    : ${name}.pem"
	echo "  ------------ Creating the file with the private key for ${name}: ${name}.key"
	sed -e s#@NAME@#"$name"# ${OPENSSL_CONF_TEMPLATE} > ssl-tmp.cnf
	openssl req -config ssl-tmp.cnf -new -x509 -days 3650 -nodes -sha256 \
        	-out ${name}.pem -keyout ${name}.key
	rm ssl-tmp.cnf
done

## Criação do ficheiro com os Clientes autenticados.
cat client1.pem client2.pem client3.pem > authentic-clients.pem

## Aceitação dos certicados por parte do Servidor em Java.
for ENT in client1 client2 client3; do
	echo "yes"|keytool -import -alias ${ENT} -keystore serverJ.jks -file ${ENT}.pem -storepass ${STOREPASS}
done
keytool -list -keystore serverJ.jks -storepass ${STOREPASS}
